### ISSUE TITLE
UK HESA -- selecting work

### ISSUE THREAD

**Issue by dragondave** [dragondave/cameron_diversity#2]
Which tables are the priority for UK HESA?

**Comment by cameronneylon** [comment]
Hi Sorry! Didn't get the issue notification for some reason. I'll make sure I'm following properly.

For HESA the priorities are the staff demographic tables by university. For the later material this is 2a,b,c and then there are similar tables earlier on. As a general rule we are focussed on university level demographic staff data, so not the stuff that is sector-wide.

**Comment by dragondave** [comment]
Thanks!

**Comment by dragondave** [comment]
Tables being considered:

HESA_Resources_1994_95/resources_1994-95_table_19b.pdf              
HESA_Resources_1995_96/resources_1995-96_table_19b.pdf              
HESA_Resources_1996_97/resources_1996-97_table_19b.pdf              
HESA_Resources_1997_98/resources_1997-98_table_19b.pdf              
HESA_Resources_1998_99/resources_1998-99_table_19b.pdf              
HESA_Resources_1999_00/resources_1999-2000_table_19b.pdf            
2000-01/Main_Tables/Table_19b.csv                                   
2000-01/Main_Tables/Table_19b.xls                                   
2001-02/Main_Tables/Table19b.csv                                    
2002-03/Tables/Staff/table_16.xls                                   
2002-03/Tables/Staff/table_17.xls                                   
2002-03/Tables/Staff/table_18.xls                                   
2003-04/tables/Staff/table_23.xls                                   
2004-05/tables/Staff/Table_23a.xls                                  
2004-05/tables/Staff/Table_23b.xls                                  
2005-06/Tables/Staff/Table_23a.xls                                  
2005-06/Tables/Staff/Table_23b.xls                                  
2006-07/tables/Table_23a.xls                                        
2006-07/tables/Table_23b.xls                                        
2007-08/tables/Table_23a.xls                                        
2007-08/tables/Table_23b.xls                                        
2008-09/tables/Table_23a.xls                                        
2008-09/tables/Table_23b.xls                                        
HESA_Staff_2009_10/tables/Staff_0910_Table_2a.xls                   
HESA_Staff_2009_10/tables/Staff_0910_Table_2b.xls                   
HESA_Staff_2009_10/tables/Staff_0910_Table_2c.xls                   
HESA_Staff_2009_10/tables/Staff_0910_Table_2d.xls                   
2010-11/tables/Staff_1011_Table_2a.xls                              
2010-11/tables/Staff_1011_Table_2b.xls                              
2010-11/tables/Staff_1011_Table_2c.xls                              
2010-11/tables/Staff_1011_Table_2d.xls                              
2011-12/tables/staff_1112_table_2a.xls                              
2011-12/tables/staff_1112_table_2b.xls                              
2011-12/tables/staff_1112_table_2c.xls                              
2011-12/tables/staff_1112_table_2d.xls                              
HESA_Staff_2012_13/tables/staff_1213_all_main_tables.xlsx           
HESA_Staff_2013_14/tables/staff_1314_all_main_tables.xlsx           
HESA_Staff_2014_15/tables/staff_1415_all_main_tables.xlsx           
HESA_Staff_2015_16/tables/staff_1516_all_main_tables.xlsx           
HESA_Staff_2016_17/tables/staff_1617_all_main_tables.xlsx
